ckpt_path : Null
ref_audio:
  # - name: test01
  #   wav_path: "/mnt/home/idgebru/Data/urban-soundscapes/"
  #   recording_ids: "${merge: ${range:1,3,1}, ${range:22,34,1}, ${range:36,64,1}}"
  #   start: -20.0
  #   length: 15.0
  #   scale: 1.0
  - name: test02
    wav_path: "/mnt/home/idgebru/Data/urban-soundscapes/"
    recording_ids: "${merge: ${range:69,76,1}, ${range:90,95,1}, [99, 101], ${range:103,118,1}, ${range:120,133,1}}"
    start: -20.0
    length: 15.0
    scale: 1.0
output:
  fld_path: "/mnt/home/idgebru/A2B_ICASSP2025/Urbansounds_good/"
  tag": "version_0"
  subtag": "0"
